version: "3.8" # this version is for docker-compose-file version

services:
  mongo:
    image: mongo
    ports:
      - 3456:27017 # you can specify the port number on the host, e.g., - 3003:27017 (27017 is the default port for mongo)
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: ## use a bind-mount to mount the file mongo-init.js to the container. The formula is: FILE-IN-HOST:FILE-IN-CONTAINER. The location of the mongo-init.js in the container side can be found from the docker hub for mongo: https://hub.docker.com/_/mongo
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db # The volume: /my/own/datadir:/data/db part of the command mounts the /my/own/datadir directory from the underlying host system as /data/db inside the container, where MongoDB by default will write its data files.
